---
- name: Check currently installed semaphore version
  ansible.builtin.command:
    cmd: "{{ semaphore_bin_path }} version"
  register: semaphore_installed_version
  changed_when: false
  failed_when: false

- name: Set semaphore needs install fact
  ansible.builtin.set_fact:
    semaphore_needs_install: >-
      {{
        semaphore_installed_version.rc != 0 or
        semaphore_version not in semaphore_installed_version.stdout
      }}

- name: Install semaphore from deb
  ansible.builtin.apt:
    deb: "{{ semaphore_deb_url }}"
  become: true
  when:
    - semaphore_needs_install
    - ansible_os_family == 'Debian'

- name: Install semaphore from rpm
  ansible.builtin.dnf:
    name: "{{ semaphore_rpm_url }}"
    state: present
    disable_gpg_check: true
  become: true
  when:
    - semaphore_needs_install
    - ansible_os_family == 'RedHat'
