---
- name: Include dependency installation
  ansible.builtin.import_tasks: dependencies.yml

- name: Include service user setup
  ansible.builtin.import_tasks: user.yml

- name: Include semaphore binary installation
  ansible.builtin.import_tasks: install.yml

- name: Include semaphore configuration and service setup
  ansible.builtin.import_tasks: configure.yml

- name: Include optional Caddy / xcaddy setup
  ansible.builtin.include_tasks: caddy.yml
  when: semaphore_install_xcaddy | bool

- name: Include database installation and setup
  ansible.builtin.import_tasks: database.yml
