---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  become: true

- name: Restart semaphore
  ansible.builtin.systemd:
    name: semaphore
    state: restarted
    daemon_reload: true
  become: true

- name: Restart caddy
  ansible.builtin.systemd:
    name: caddy
    state: restarted
    daemon_reload: true
  become: true
